name: vanilla

dependencies:
  - base

executables:
  vanilla:
    main: vanilla.hs
    source-dirs:
      - src

tests:
  spec:
    main: Main.hs
    source-dirs:
      - test
      - src
    dependencies:
      - hspec
