name: vanilla-haskell

dependencies:
  - base

executables:
  foo:
    main: Main.hs
    source-dirs:
      - src

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
      - src
    dependencies:
      - hspec
