name: vanilla

dependencies:
  - base
  - aeson
  - basement
  - cassava
  - conduit
  - containers
  - foundation
  - generics-eot
  - getopt-generics
  - graph-wrapper
  - optparse-applicative
  - pipes
  - rio
  - servant
  - servant-client
  - servant-server
  - shake
  - string-conversions
  - text
  - unordered-containers
  - vector
  - yaml
  - yesod

executables:
  vanilla:
    main: vanilla.hs
    source-dirs:
      - src

tests:
  spec:
    main: Main.hs
    source-dirs:
      - test
      - src
    dependencies:
      - hspec
      - mockery
      - silently
      - temporary
